[project]
name = "car-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=1.3.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
car-agent = "car_agent:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
